local opt = vim.opt

opt.number = true
opt.relativenumber = true
opt.autoindent = true
opt.splitright = true
opt.splitbelow = true
opt.ignorecase = true
opt.smartcase = true
opt.termguicolors = true
opt.wrap = true
opt.breakindent = true
opt.scrolloff = 10
opt.cursorline = true
opt.expandtab = true
opt.tabstop = 3
opt.shiftwidth = 3
opt.ruler = true
opt.mouse = 'a'
opt.title = true
opt.wildmenu = true
--opt.clipboard = "unamedplus"
--opt.hidden = true
--opt.encoding = 'UTF-8'
--opt.ttimeoutlen = 0
opt.showcmd = true
opt.showmatch = true
